trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: user-service
  acrName: microacr123

steps:

# 🔹 Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

# 🔹 Install dependencies
- script: |
    cd user-service
    npm install
  displayName: 'Install dependencies'

# 🔹 Build and Push Docker Image to ACR
- task: Docker@2
  displayName: 'Build and Push Image to ACR'
  inputs:
    containerRegistry: 'ACR-Service-Connection'
    repository: 'user-service'
    command: 'buildAndPush'
    Dockerfile: 'user-service/Dockerfile'
    tags: |
      latest
      $(Build.BuildId)

# 🔹 Deploy to AKS
- task: KubernetesManifest@0
  displayName: 'Deploy to AKS'
  inputs:
    action: deploy
    kubernetesServiceConnection: 'AKS-Service-Connection'
    namespace: default
    manifests: |
      k8s/deployment.yaml
      k8s/service.yaml